name: TapTender
favicon: null
layout_spectrum: 0.26226
typography_spectrum: 0.9745587788056582
title: Toite tellimise app
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e6e6'
    - '#ffffff'
    - '#cccccc'
    - '#ff6723'
    - '#ff9e67'
  brandStrength: 0.9983377135358751
  lightness: 0.8799148914404213
  saturation: 0.9346451300662011
  rhythmicContrast: 0.7639478428754956
purpose: []
